# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab1.4.5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(772, 563)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(420, 80, 211, 131))
        self.groupBox.setObjectName("groupBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(40, 50, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(150, 50, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.MplWidget = mplwidget(Form)
        self.MplWidget.setGeometry(QtCore.QRect(30, 80, 311, 251))
        self.MplWidget.setObjectName("MplWidget")
        self.pushButton_2 = SaveToFile(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 240, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
from mplwidget import mplwidget
from savetofile import SaveToFile
